stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: wahyukac0401/httpd:${CICD_EXECUTION_SEQUENCE}
      pushRemote: 
      registry: prod-registry01
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
