stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: httpd:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: wahyukac0401
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
