stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: prod-registry01.pln.co.id/test-prod/httpd:${CICD_EXECUTION_SEQUENCE}
      pushRemote: false
      registry: prod-registry01.pln.co.id:443
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
