stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: prod-registry01.pln.co.id/master-image/httpd:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: prod-registry01
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
