stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: prod-registry01.pln.co.id/test-prod/httpd:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: prod-registry01.pln.co.id
    env:
      PLUGIN_INSECURE: "true"
      PLUGIN_DEBUG: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
