stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: wahyukac0401/httpd:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_INSECURE: "false"
      PLUGIN_DEBUG: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
