kind: Service
apiVersion: v1
metadata:
  name: httpd
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      imagePullSecrets:
      - name: wahyukac
      containers:
      - name: httpd
        image: wahyukac0401/httpd:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
